CREATE DATABASE Bamazon

USE DATABASE Bamazon

CREATE TABLE products (
	ItemID INT(11) NOT NULL AUTO_INCREMENT,
	ProductName VARCHAR(150) DEFAULT NULL,
	DepartmentName VARCHAR(100) DEFAULT NULL,
	Price DECIMAL (6,2) DEFAULT '0.00' NOT NULL,
	StockQuantity INT(11) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ItemID)
)
